### ISSUE TITLE
Nothing happens when trying to run kitchen command

### ISSUE THREAD

**Issue by AlexKiaie** [jirkafajfr/vscode-kitchen#11]
When I try to run any of the kitchen commands from VSCode, nothing actually executes. It switches the output window to the Test Kitchen dropdown option but nothing actually executes and there are no logs in the kitchen logs.

I'm on win 7 64-bit VS Code version 1.2.1

**Comment by jirkafajfr** [comment]
Hi Alex,

this was windows specific problem and should be fixed by commit 96629d39b91de004e475b1667b048ea12bcfd95c. Let me push new 0.0.3 version to the supermarket

**Comment by AlexKiaie** [comment]
works now. thank you for the amazingly quick turnaround
