### ISSUE TITLE
Cannot kill current running kitchen process

### ISSUE THREAD

**Issue by AKiaieHiebing** [jirkafajfr/vscode-kitchen#12]
If I run a kitchen command with the extension, but need to kill it, or worse when ssh is not connecting, the process cannot be aborted. If I try to run another kitchen command it asks if I want to abort the current process, but clicking yes does nothing. I have to close VS Code and reopen it to recover from this state.

**Comment by jirkafajfr** [comment]
The problem was in killing of just parent process (child processes were left to run).  That should be fixed now.

But extension is still lacking any "direct termination" command. The only way is to run different kitchen command and agree with termination of previous process.

Do you have idea how this could be handled better from user perspective?

**Comment by AlexKiaie** [comment]
Best thing i can think of off the top of my head is a specific command in the kitchen command list that shows up on the command bar to terminate. Or if it's possible to run the commands in a terminal instead of just the output window then the user could kill the process.

**Comment by jirkafajfr** [comment]
@AlexKiaie: Once you register commands in VSCode command palette you can't easily hide them. I was quite hesitant to just adding "kill process" command which could be invoked even when nothing is running.

I come up with this idea that you can kill background process when clicking on status bar progress item (which is visible only when kitchen process is running)
![converge](https://cloud.githubusercontent.com/assets/2222675/17281080/b32f89b4-575e-11e6-8d06-ae919ae0595b.gif)

Checkout new version and let me know what you think.

P.S. If you need termination command in command palette from some reason you can create custom key binding and associate it with following command: `kitchen.terminateProcess`

**Comment by AlexKiaie** [comment]
Good enhancement. Works like a charm and thanks for the heads up for the custom key binding
